### ISSUE TITLE
🍃 Upgrade SpringBoot 3 : impact Spring Native ❌

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/api-partenaires-mobilis#210]
Bon, en effet le spriboot native a changé avec la v3 : 

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/39691264/210672288-601cbdf0-edfd-4587-a795-3ebc8648ac32.png">

_Originally posted by @Dougniel in https://github.com/opt-nc/api-partenaires-mobilis/issues/207#issuecomment-1371559566_

**Comment by Dougniel** [comment]
Bon ça commence mal, sur la base d'un code généré par Spring Initializr :

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/39691264/210676643-e7169e6a-f2e9-4d4d-9eee-d512410be0ea.png">

Là je dis bravo 👍 :trollface: 🥇

**Comment by Dougniel** [comment]
Bug présent, c'est liée à devtools qui marche pas avec spring native : https://github.com/spring-projects/spring-boot/issues/32853

Si j'enlève devtools, je me retrouve avec un autre problème : les resources ne sont plus incluses dans l'exécutable (les *.csv) du coup l'appel de l'API retourne une liste vide ❌😳

**Comment by Dougniel** [comment]
> * je me retrouve avec un autre problème : les resources ne sont plus incluses dans l'exécutable (les *.csv) du coup l'appel de l'API retourne une liste vide ❌😳

Problème réglé grâce à [ce ticket](https://github.com/spring-projects/spring-boot/issues/33400), mais un nouveau problème se cache derrière lors de l'appel à l'API : 

```
2023-01-06T10:53:06.989+11:00  INFO 25020 --- [nio-8080-exec-1] o.h.e.internal.DefaultLoadEventListener  : HHH000327: Error performing load command

org.hibernate.HibernateException: Generation of HibernateProxy instances at runtime is not allowed when the configured BytecodeProvider is 'none'; your model requires a more advanced BytecodeProvider to be enabled.
        at org.hibernate.bytecode.internal.none.DisallowedProxyFactory.getProxy(DisallowedProxyFactory.java:34) ~[na:na]
        at org.hibernate.persister.entity.AbstractEntityPersister.createProxy(AbstractEntityPersister.java:5001) ~[api-partenaires-mobilis:6.1.6.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.createProxy(DefaultLoadEventListener.java:463) ~[na:na]
        at org.hibernate.event.internal.DefaultLoadEventListener.createProxyIfNecessary(DefaultLoadEventListener.java:453) ~[na:na]
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:357) ~[na:na]
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:113) ~[na:na]
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:75) ~[na:na]
 ```

**Comment by Dougniel** [comment]
> Ca ressemble en fait au souci des bdd en mem sur Quarkus où ne puvat pas faire de natif non ?

Pas vraiment, cette limitation était propre à H2 en mémoire avec Quarkus

Là il s'agit d'Hibernate donc on pourrait se dire que cela pourrait arriver avec n'importe quel type de base de données

**Comment by Dougniel** [comment]
https://github.com/opt-nc/api-partenaires-mobilis/pull/213

**Comment by Dougniel** [comment]
> 

C'est un bug Spring-Boot en natif : https://github.com/spring-projects/spring-framework/issues/29779

👉🏼 J'ai mis en place un contournement référencé et ça passe (pour le moment)

⁉️ Ce que je ne comprends pas, c'est que c'est quelque-chose d'assez classique (lorsqu'on fait du Lazy Loading), je ne comprends pas que ce problème ne soit pas déjà remonté et corrigé 🤨.. ou bien pas grand monde ne fait du Spring Native :trollface:

**Comment by Dougniel** [comment]
L'image Docker native n'a pas été déployée 😅

**Comment by Dougniel** [comment]
L'url du swagger ne fonctionne plus

**Comment by Dougniel** [comment]
Bah voillons 💩 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/39691264/216869567-7fe84b05-7a02-44c2-91a4-d164f0a0bf19.png">

**Comment by Dougniel** [comment]
https://github.com/opt-nc/api-partenaires-mobilis/commit/cad3dea92670a2e41b44932b12525a80d526ec66

**Comment by Dougniel** [comment]
✅ C'est bon, testé livré https://killercoda.com/opt-labs/course/partenaires-mobilis/partenaires-mobilis-discover
